In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # visualization
import matplotlib.pyplot as plt

%matplotlib inline


In [ ]:
# load database
data = pd.read_csv("/content/drive/My Drive/College/6th Sem/ML/Lab/nba_logreg.csv")
data.dropna(inplace=True)
data.sample(n=5)

name  gp   min  pts  fgm  ...  ast  stl  blk  tov  target_5yrs
162    Charles Smith  60   8.7  2.9  1.0  ...  1.7  0.6  0.1  0.6          1.0
1318   Anthony Avent  82  27.9  9.8  4.2  ...  1.1  0.7  0.9  1.7          1.0
411    Paul Thompson  82  21.1  9.0  3.8  ...  1.5  0.8  0.5  0.9          0.0
456   Brandon Davies  51  11.3  2.8  1.1  ...  0.5  0.5  0.2  0.7          0.0
1248  Derrick Alston  64  16.1  4.7  1.9  ...  0.5  0.6  0.6  0.8          0.0

[5 rows x 21 columns]

In [ ]:
data = data.drop(columns=["name"])
df_norm = data[["gp", "min", "pts", "fgm", "fga", "fg","3p_made", "3pa", "3p", "ftm", "fta", "ft", "oreb", "dreb", "reb", "ast", "stl", "blk", "tov"]].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
df_norm.head()

gp       min       pts       fgm  ...       ast   stl       blk       tov
0  0.352113  0.642857  0.243636  0.232323  ...  0.179245  0.16  0.102564  0.279070
1  0.338028  0.629630  0.236364  0.171717  ...  0.349057  0.44  0.128205  0.348837
2  0.887324  0.322751  0.163636  0.171717  ...  0.094340  0.20  0.076923  0.209302
3  0.661972  0.224868  0.181818  0.202020  ...  0.075472  0.24  0.025641  0.209302
4  0.521127  0.222222  0.138182  0.131313  ...  0.028302  0.12  0.102564  0.162791

[5 rows x 19 columns]

In [ ]:
target = data[['target_5yrs']]
target.sample(n=5)

target_5yrs
299           0.0
213           1.0
1101          1.0
843           0.0
276           1.0

In [ ]:
df = pd.concat([df_norm, target], axis=1)
df.sample(n=5)

gp       min       pts  ...       blk       tov  target_5yrs
1093  0.239437  0.722222  0.203636  ...  0.153846  0.255814          1.0
337   0.802817  0.253968  0.163636  ...  0.025641  0.186047          0.0
51    0.549296  0.148148  0.065455  ...  0.025641  0.209302          1.0
438   0.056338  0.126984  0.043636  ...  0.025641  0.209302          0.0
486   0.394366  0.097884  0.054545  ...  0.025641  0.093023          1.0

[5 rows x 20 columns]

In [ ]:
train_test_per = 80/100.0
df['train'] = np.random.rand(len(df)) < train_test_per
df.sample(n=5)

gp       min       pts  ...       tov  target_5yrs  train
811  0.647887  0.854497  0.585455  ...  0.441860          1.0   True
23   0.704225  0.701058  0.410909  ...  0.558140          0.0   True
180  0.140845  0.026455  0.054545  ...  0.046512          0.0   True
205  1.000000  0.359788  0.163636  ...  0.162791          1.0   True
269  0.352113  0.084656  0.021818  ...  0.093023          1.0   True

[5 rows x 21 columns]

In [ ]:
train = df[df.train == 1]
train = train.drop('train', axis=1).sample(frac=1)
train.sample(n=5)

gp       min       pts  ...       blk       tov  target_5yrs
489  0.338028  0.029101  0.080000  ...  0.025641  0.069767          0.0
232  0.450704  0.097884  0.032727  ...  0.025641  0.069767          1.0
883  0.169014  0.150794  0.098182  ...  0.025641  0.069767          1.0
952  0.070423  0.034392  0.018182  ...  0.000000  0.069767          1.0
633  0.746479  0.552910  0.261818  ...  0.102564  0.139535          1.0

[5 rows x 20 columns]

In [ ]:
test = df[df.train == 0]
test = test.drop('train', axis=1)
test.sample(n=5)

gp       min       pts  ...       blk       tov  target_5yrs
696  0.422535  0.055556  0.047273  ...  0.051282  0.093023          0.0
532  0.436620  0.100529  0.105455  ...  0.025641  0.116279          1.0
450  0.873239  0.537037  0.352727  ...  0.076923  0.418605          1.0
617  0.647887  0.214286  0.123636  ...  0.128205  0.139535          1.0
479  0.408451  0.182540  0.043636  ...  0.076923  0.093023          0.0

[5 rows x 20 columns]

In [ ]:
X = train.values[:,:19]
X[:5]

array([[0.95774648, 0.3042328 , 0.16727273, 0.16161616, 0.2       ,
        0.34669339, 0.13043478, 0.15384615, 0.346     , 0.16883117,
        0.17647059, 0.702     , 0.0754717 , 0.11702128, 0.10294118,
        0.27358491, 0.28      , 0.07692308, 0.3255814 ],
       [0.76056338, 0.17195767, 0.15636364, 0.17171717, 0.14736842,
        0.61122244, 0.        , 0.        , 0.        , 0.14285714,
        0.16666667, 0.642     , 0.13207547, 0.07446809, 0.09558824,
        0.04716981, 0.12      , 0.        , 0.1627907 ],
       [0.69014085, 0.16402116, 0.07636364, 0.08080808, 0.09473684,
        0.33667335, 0.17391304, 0.16923077, 0.394     , 0.03896104,
        0.03921569, 0.64      , 0.03773585, 0.04255319, 0.02941176,
        0.18867925, 0.2       , 0.        , 0.23255814],
       [0.67605634, 0.68253968, 0.32      , 0.33333333, 0.43684211,
        0.32665331, 0.34782609, 0.41538462, 0.306     , 0.19480519,
        0.17647059, 0.798     , 0.13207547, 0.23404255, 0.21323529,
        0.264

In [ ]:
targets = [[1,0],[0,1]]
y = np.array([targets[int(x)] for x in train.values[:,19:20]])
y[:5]

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0]])

In [ ]:
num_inputs = len(X[0])
hidden_layer_neurons1 = 6
np.random.seed(4)
w1 = 2*np.random.random((num_inputs, hidden_layer_neurons1)) - 1
print(w1)
num_outputs = len(y[0])
w2 = 2*np.random.random((hidden_layer_neurons1, num_outputs)) - 1
w2

[[ 0.93405968  0.0944645   0.94536872  0.42963199  0.39545765 -0.56782101]
 [ 0.95254891 -0.98753949 -0.49403528 -0.13041694  0.55876584 -0.60462985]
 [ 0.72598647  0.96680135 -0.67231552  0.19466789 -0.9820278  -0.22685743]
 [-0.91167988  0.91330594 -0.12770671  0.89795461  0.57261197  0.7325786 ]
 [-0.65366916 -0.85010283  0.20148544 -0.66405563  0.46676034 -0.18311228]
 [ 0.05581765  0.87514317  0.04339224 -0.78361323 -0.68355319  0.0904053 ]
 [ 0.04880816  0.27522049 -0.19700911  0.29961022 -0.20619999  0.24783223]
 [ 0.53480993 -0.64205218 -0.24884846  0.00506612  0.37333416 -0.4926407 ]
 [ 0.10948173  0.24986169  0.79100233 -0.27429282  0.27511415 -0.6171072 ]
 [-0.00441177 -0.63510919  0.83676608 -0.13635586  0.6603762  -0.16644739]
 [ 0.80933518 -0.19034957 -0.33765099  0.14427754  0.6908873   0.72202862]
 [ 0.19137623 -0.83067678  0.19453321 -0.50909258  0.4651869   0.78930258]
 [ 0.02946794  0.20712702 -0.86986438  0.08014946 -0.74162643  0.22912569]
 [-0.27269931  0.53551607

array([[ 0.51905906,  0.58884664],
       [-0.18274643,  0.88759501],
       [-0.65244041,  0.8851717 ],
       [-0.06902065,  0.52598728],
       [ 0.50564039,  0.96241984],
       [ 0.94655599, -0.91981775]])

In [ ]:
learning_rate = 0.2 # slowly update the network
for epoch in range(500000):
    l1 = 1/(1 + np.exp(-(np.dot(X, w1)))) # sigmoid function
    l2 = 1/(1 + np.exp(-(np.dot(l1, w2))))
    er = (abs(y - l2)).mean()
    l2_delta = (y - l2)*(l2 * (1-l2))
    l1_delta = l2_delta.dot(w2.T) * (l1 * (1-l1))
    w2 += l1.T.dot(l2_delta) * learning_rate
    # print('LLLL :', w2)
    w1 += X.T.dot(l1_delta) * learning_rate
print('Error:', er)

Error: 0.14062355265684476


In [ ]:
X = test.values[:,:19]
y = np.array([targets[int(x)] for x in test.values[:,19:20]])

l1 = 1/(1 + np.exp(-(np.dot(X, w1))))
l2 = 1/(1 + np.exp(-(np.dot(l1, w2))))
np.round(l2,3)

array([[0.931, 0.069],
       [0.5  , 0.5  ],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [0.986, 0.014],
       [0.053, 0.947],
       [0.053, 0.947],
       [0.   , 1.   ],
       [0.867, 0.133],
       [0.499, 0.501],
       [0.053, 0.947],
       [0.074, 0.926],
       [0.5  , 0.5  ],
       [0.053, 0.947],
       [0.5  , 0.5  ],
       [0.479, 0.521],
       [0.053, 0.947],
       [0.5  , 0.5  ],
       [0.053, 0.947],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [0.016, 0.984],
       [1.   , 0.   ],
       [0.053, 0.947],
       [0.5  , 0.5  ],
       [0.053, 0.947],
       [0.053, 0.947],
       [1.   , 0.   ],
       [0.983, 0.017],
       [0.976, 0.024],
       [0.   , 1.   ],
       [0.5  , 0.5  ],
       [0.446, 0.554],
       [0.446, 0.554],
       [0.446, 0.554],
       [0.541, 0.459],
       [1.   , 0.   ],
       [0.053, 0.947],
       [0.053, 0.947],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.022, 0.978],
       [1.   , 0.   ],
       [0. 

In [ ]:
yp = np.argmax(l2, axis=1) # prediction
res = yp == np.argmax(y, axis=1)
correct = np.sum(res)/len(res)

testres = test[['target_5yrs']]

testres['Prediction'] = yp
# testres['Prediction'] = testres['Prediction'].replace([0.0,1.0], ['No','Yes'])

print(testres)
print('Correct:',sum(res),'/',len(res), ':', (correct*100),'%')

      target_5yrs  Prediction
5             0.0           0
7             1.0           0
11            1.0           1
16            0.0           0
17            0.0           0
...           ...         ...
1327          1.0           1
1329          0.0           0
1330          1.0           1
1332          1.0           0
1335          0.0           1

[275 rows x 2 columns]
Correct: 238 / 275 : 86.54545454545455 %


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


**RELU**

In [ ]:
num_inputs = len(X[0])
hidden_layer_neurons1 = 6
np.random.seed(4)
w1 = 2*np.random.random((num_inputs, hidden_layer_neurons1)) - 1
print(w1)
num_outputs = len(y[0])
w2 = 2*np.random.random((hidden_layer_neurons1, num_outputs)) - 1
w2

[[ 0.93405968  0.0944645   0.94536872  0.42963199  0.39545765 -0.56782101]
 [ 0.95254891 -0.98753949 -0.49403528 -0.13041694  0.55876584 -0.60462985]
 [ 0.72598647  0.96680135 -0.67231552  0.19466789 -0.9820278  -0.22685743]
 [-0.91167988  0.91330594 -0.12770671  0.89795461  0.57261197  0.7325786 ]
 [-0.65366916 -0.85010283  0.20148544 -0.66405563  0.46676034 -0.18311228]
 [ 0.05581765  0.87514317  0.04339224 -0.78361323 -0.68355319  0.0904053 ]
 [ 0.04880816  0.27522049 -0.19700911  0.29961022 -0.20619999  0.24783223]
 [ 0.53480993 -0.64205218 -0.24884846  0.00506612  0.37333416 -0.4926407 ]
 [ 0.10948173  0.24986169  0.79100233 -0.27429282  0.27511415 -0.6171072 ]
 [-0.00441177 -0.63510919  0.83676608 -0.13635586  0.6603762  -0.16644739]
 [ 0.80933518 -0.19034957 -0.33765099  0.14427754  0.6908873   0.72202862]
 [ 0.19137623 -0.83067678  0.19453321 -0.50909258  0.4651869   0.78930258]
 [ 0.02946794  0.20712702 -0.86986438  0.08014946 -0.74162643  0.22912569]
 [-0.27269931  0.53551607

array([[ 0.51905906,  0.58884664],
       [-0.18274643,  0.88759501],
       [-0.65244041,  0.8851717 ],
       [-0.06902065,  0.52598728],
       [ 0.50564039,  0.96241984],
       [ 0.94655599, -0.91981775]])

In [ ]:
def reluDerivative(x):
  x = (er > 0) * 1.00
  return x

In [ ]:
learning_rate = 0.01 # slowly update the network
for epoch in range(10000):
    l1 = np.dot(X, w1) # sigmoid function
    np.maximum(l1, 0)
    l2 = np.dot(l1, w2)
    np.maximum(l2, 0)
    er = (abs(y - l2)).mean()
    print(w2)
    l2_delta = (y - l2)*reluDerivative(l2)
    l1_delta = l2_delta.dot(w2.T) * reluDerivative(l1)
    w2 += l1.T.dot(l2_delta) * learning_rate
    # print('LLLL :', w2)
    w1 += X.T.dot(l1_delta) * learning_rate
print('Error:', er)

[[ 0.51905906  0.58884664]
 [-0.18274643  0.88759501]
 [-0.65244041  0.8851717 ]
 [-0.06902065  0.52598728]
 [ 0.50564039  0.96241984]
 [ 0.94655599 -0.91981775]]
Error: 0.8045441565926893


In [ ]:
X = test.values[:,:19]
y = np.array([targets[int(x)] for x in test.values[:,19:20]])

l1 = np.dot(X, w1)
np.maximum(l1, 0)
l2 = np.dot(l1, w2)
np.maximum(l2, 0)
np.round(l2,3)

array([[ 1.317, -4.099],
       [ 1.641, -3.368],
       [ 1.002, -3.865],
       [ 1.152, -2.735],
       [ 2.376, -4.447],
       [ 1.535, -4.331],
       [ 0.981, -3.185],
       [ 1.738, -5.456],
       [ 1.825, -5.424],
       [ 1.366, -4.465],
       [ 1.307, -4.057],
       [ 1.688, -3.355],
       [ 1.307, -2.805],
       [ 1.71 , -3.558],
       [ 1.175, -2.817],
       [ 2.243, -4.696],
       [ 2.495, -4.253],
       [ 1.326, -3.511],
       [ 2.902, -5.777],
       [ 2.319, -6.262],
       [ 1.765, -5.032],
       [ 1.603, -4.591],
       [ 2.042, -3.971],
       [ 1.002, -3.981],
       [ 1.431, -2.937],
       [ 1.376, -2.855],
       [ 1.095, -3.42 ],
       [ 1.384, -3.494],
       [ 0.838, -2.537],
       [ 2.504, -7.34 ],
       [ 1.831, -5.572],
       [ 2.057, -4.885],
       [ 2.116, -4.627],
       [ 2.412, -4.132],
       [ 1.347, -5.012],
       [ 1.702, -3.285],
       [ 1.41 , -3.761],
       [ 2.8  , -4.496],
       [ 3.115, -5.475],
       [ 2.835, -5.292],


In [ ]:
yp = np.argmax(l2, axis=1) # prediction
res = yp == np.argmax(y, axis=1)
correct = np.sum(res)/len(res)

testres = test[['target_5yrs']]

testres['Prediction'] = yp
# testres['Prediction'] = testres['Prediction'].replace([0.0,1.0], ['No','Yes'])

print(testres)
print('Correct:',sum(res),'/',len(res), ':', (correct*100),'%')

      target_5yrs  Prediction
2             0.0           0
4             1.0           0
5             0.0           0
16            0.0           0
27            1.0           0
...           ...         ...
1299          0.0           0
1309          1.0           0
1314          1.0           0
1321          1.0           0
1335          0.0           0

[133 rows x 2 columns]
Correct: 52 / 133 : 39.097744360902254 %


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
